---
engines:
  fixme:
    enabled: true
  pep8:
    enabled: true
  radon:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
ratings:
  paths:
  - "**.py"
exclude_paths:
- tests/**/*
- config/**/*
- vendor/**/*
